### PR TITLE
Fixes #280. Problem spec intact.

### LINKED ISSUE #280: all-your-base has an incorrect test case
The [test case](https://github.com/exercism/cpp/blob/master/exercises/all-your-base/all_your_base_test.cpp#L105) `leading_zeros` is incorrect in my opinion.
Also, I think it might be better that the invalid cases throw an std::error instead of returning 0.

### PR DESCRIPTION
**Pull request by anupamsobti**
Fixes #280 without modifying base 1 behavior. Fixes `leading_zeros` test case and requires `std::error` for test cases where the base is invalid.

### CODE REVIEW

File: exercises/all-your-base/all_your_base_test.cpp [hunk 1]
```diff
@@ -102,50 +102,35 @@ TEST_CASE("multiple_zeros") {
...
     REQUIRE(expected == out_digits);
 }
 
 TEST_CASE("first_base_is_one") {
     vector<unsigned int> in_digits{};
-    vector<unsigned int> expected{};
-    vector<unsigned int> out_digits = all_your_base::convert(1, in_digits, 10);
-
-    REQUIRE(expected == out_digits);
+    REQUIRE_THROWS_AS(all_your_base::convert(1, in_digits, 10), std::invalid_argument);
```
Comment (patricksjackson) [inline exercises/all-your-base/all_your_base_test.cpp]: Please add a blank line above this line in each of the test cases, just to match the visual style of the other tests.

**Comment by patricksjackson** [comment]
Oh, also you need to fix the example solution so that it passes the new tests.

**Comment by anupamsobti** [comment]
Made the changes. Kindly review.

**Comment by patricksjackson** [comment]
Looks good 👍  Thanks!
